# -*- coding: utf-8 -*-
"""Accident_Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dkty418siKUz0_B974AiTQK46Ay8EobV
"""

!pip install ultralytics

!apt-get install unrar

import os

rar_file = '/content/drive/MyDrive/AccidentsDetectionYOLOv8.rar'


output_dir = 'yolodata'
os.makedirs(output_dir, exist_ok=True)


!unrar x -o+ {rar_file} {output_dir}/


os.listdir(output_dir)

from ultralytics import YOLO


model = YOLO('yolov8n.pt')  

# Train the model
results = model.train(data='/content/data/AccidentsDetectionYOLOv8/data.yaml', epochs=20, imgsz=640)

import cv2
from ultralytics import YOLO


model = YOLO('accident_detection.pt')

cap = cv2.VideoCapture(0)


while True:

    ret, frame = cap.read()

    if not ret:
        print("Error: Failed to capture image.")
        break

    results = model(frame)


    annotated_frame = results[0].plot()
    cv2.imshow('YOLOv8 Webcam Inference', annotated_frame)

    # Press 'q' to quit
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()